# Generated by Django 2.2.6 on 2019-12-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0037_auto_20191122_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_dynmcqtest',
            name='id_student',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
