# Generated by Django 2.2.6 on 2020-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0039_auto_20200121_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyntestinfo',
            name='print_test',
            field=models.BooleanField(default=False),
        ),
    ]
