# Generated by Django 2.2.6 on 2020-01-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0040_auto_20200121_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyntestinfo',
            name='print_test',
        ),
    ]
