# Generated by Django 2.2.6 on 2020-01-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0041_remove_dyntestinfo_print_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyntestinfo',
            name='print_test',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
