# Generated by Django 2.2.6 on 2020-01-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0042_dyntestinfo_print_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyntestinfo',
            name='print_test',
            field=models.BooleanField(default=False),
        ),
    ]
