# Generated by Django 2.2.6 on 2020-01-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0043_auto_20200121_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynmcqinfo',
            name='print_test',
            field=models.BooleanField(default=False),
        ),
    ]
