# Generated by Django 2.1.7 on 2020-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, null=True)),
                ('question_level', models.CharField(choices=[('Debutant', 'Debutant'), ('Intermediaire', 'Intermediaire')], max_length=200)),
                ('question_categorie', models.ManyToManyField(to='qcm.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_text', models.CharField(max_length=200)),
                ('reponse_categorie', models.ManyToManyField(to='qcm.Categories')),
            ],
        ),
    ]
