# Generated by Django 2.1.7 on 2020-11-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_true_reponse',
            field=models.ManyToManyField(to='qcm.Reponse'),
        ),
    ]
