# Generated by Django 2.1.7 on 2020-11-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0002_question_question_true_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categorie_link',
            field=models.ManyToManyField(null=True, related_name='_categories_categorie_link_+', to='qcm.Categories'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponse_categorie',
            field=models.ManyToManyField(null=True, to='qcm.Categories'),
        ),
    ]
