# Generated by Django 2.1.7 on 2020-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0003_auto_20201105_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_false_reponse',
            field=models.ManyToManyField(related_name='false', to='qcm.Reponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_true_reponse',
            field=models.ManyToManyField(related_name='true', to='qcm.Reponse'),
        ),
    ]
