# Generated by Django 2.1.7 on 2020-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0004_auto_20201105_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_level',
            field=models.CharField(choices=[('Debutant', 'Debutant'), ('Intermediaire', 'Intermediaire'), ('Difficile', 'Difficile'), ('Extreme', 'Extreme')], max_length=200),
        ),
    ]
