# Generated by Django 2.1.7 on 2020-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0005_auto_20201105_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorie_link',
            field=models.ManyToManyField(related_name='_categories_categorie_link_+', to='qcm.Categories'),
        ),
    ]
