# Generated by Django 2.1.7 on 2020-11-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0006_auto_20201105_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorie_link',
            field=models.ManyToManyField(blank=True, null=True, related_name='_categories_categorie_link_+', to='qcm.Categories'),
        ),
    ]
