# Generated by Django 3.1.3 on 2020-11-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='question_level_in_months_of_study',
            field=models.IntegerField(unique=True),
        ),
    ]
