# Generated by Django 3.1.3 on 2020-11-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20201108_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='id_parent_category',
        ),
    ]
