# Generated by Django 3.1.3 on 2020-11-08 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_remove_answers_id_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqs',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
